version: 0.0
phases:
  install:
    runtime-versions:
            dotnet: 7.0

  pre_build:
    commands:
      - echo Restore packages started on `date`
      - dotnet restore Concord.WebPortal.sln

  build:
    commands:
      - echo Build started on `date`
      - dotnet build -c Release Concord.WebPortal.WebApi/Concord.WebPortal.WebApi.csproj

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release ./ Concord.WebPortal.WebApi/Concord.WebPortal.WebApi.csproj

artifacts:
  files:
    - '**/*'